### ISSUE TITLE
STM32F411CEU6 compile error in STM32cubeIDE

### ISSUE THREAD

**Issue by creisey** [terjeio/grblHAL#106]
hi there i tried to follow up the guide for compiling but i get an error:

In file included from ../Src/st_morpho.c:23:0:
../Src/st_morpho.c: In function 'digital_out':
../Src/st_morpho.c:30:26: error: 'AUXOUTPUT0_PORT' undeclared (first use in this function)

anyone can help?

**Comment by terjeio** [comment]
Ouch - sorry about this, is a regression from my latest update where I added my upcoming CNC breakout. I'll fix it soon.

**Comment by terjeio** [comment]
fix comitted.

**Comment by creisey** [comment]
worked like a charm!

**Comment by creisey** [comment]
compile works, but grbl not...

i tried to connect over USB & Serial but neither worked.

if i connect the stm32 to the PC no virtual serial port appears.

**Comment by creisey** [comment]
STM32F411CEU6, to be precise

**Comment by terjeio** [comment]
On a Blackpill? Do you have a link to any data about the board used?

It could be that the clock tree is not configured correctly, likely an incorrect master oscillator setting. See the [driver page](https://github.com/terjeio/grblHAL/tree/master/drivers/STM32F4xx): there is a configuration for the crystal frequency, `HSE_VALUE` that might need to be changed to match your board.

**Comment by terjeio** [comment]
I've just tested a Blackpill with a 25MHz crystal. On my development machine it did not show up and I could not see any code changes explaining it. Since I have an USB hub that plays games with me I plugged it into a laptop - and it showed up there and worked. When I brought it back to my development machine it showed up there as well - and worked... Spooky. FYI the last couple of days I have worked extensively on the F4xx driver with a F411 Nucleo-board using UART comms, no problems related to that.

Do you have another machine you can try your board with?

**Comment by creisey** [comment]
> I've just tested a Blackpill with a 25MHz crystal. On my development machine it did not show up and I could not see any code changes explaining it. Since I have an USB hub that plays games with me I plugged it into a laptop - and it showed up there and worked. When I brought it back to my development machine it showed up there as well - and worked... Spooky. FYI the last couple of days I have worked extensively on the F4xx driver with a F411 Nucleo-board using UART comms, no problems related to that.
> 
> Do you have another machine you can try your board with?
![20201030_070321](https://user-images.githubusercontent.com/19647655/97666916-f09db180-1a7e-11eb-917a-364416f58c10.jpg)
this is a picture of my board.
and i bought it here: https://de.aliexpress.com/item/4000138305460.html?spm=a2g0s.9042311.0.0.27424c4dh6OnLS


i'll try it on another machine.
![image](https://user-images.githubusercontent.com/19647655/97666586-4e7dc980-1a7e-11eb-8fc4-2d349ba13962.png)
no serial appears

**Comment by terjeio** [comment]
Have you changed the STM32F401xC symbol to STM32F411xE as descriped in the driver readme? In fact you have to remove STM32F401xC and add STM32F411xE

**Comment by creisey** [comment]
i did
![image](https://user-images.githubusercontent.com/19647655/97706552-2dd16600-1ab6-11eb-8c61-17a9ee4494fd.png)

**Comment by terjeio** [comment]
Thanks, your board is not a [Nucleo 64 board](https://www.st.com/en/evaluation-tools/nucleo-f411re.html)... Remove NUCLEO_F411 and try again  - hopefully then it will work.

**Comment by creisey** [comment]
thx for your assistance! after removing nucleo board it worked

**Comment by creisey** [comment]
the io-GCode Sender is one of the best i've used so far!
