### ISSUE TITLE
HOW TO COMPILE

### ISSUE THREAD

**Issue by irshadmgs011** [terjeio/grblHAL#110]
I reade wiki but i don't understand how to compile code, i want to compile SAM3X8E

**Comment by terjeio** [comment]
Did you try to follow the instructions in in [this Wiki page](https://github.com/terjeio/grblHAL/wiki/Compiling-GrblHAL)? If so what exactly didn't you understand?

**Comment by irshadmgs011** [comment]
@terjeio Yes i read but i don't understand, this instruction is not simple, just like merlin and esp32 grbl, Can you make a video tutorial

**Comment by terjeio** [comment]
I have made a .zip-library for you, import this in your Arduino IDE with _Sketch > Include Library > Add .ZIP library..._
After doing that you should find _grblHAL for Due_ under _File > Examples_ for you to compile and upload.

[grblHAL_Due.zip](https://github.com/terjeio/grblHAL/files/5526641/grblHAL_Due.zip)

**Comment by irshadmgs011** [comment]
![Captures](https://user-images.githubusercontent.com/22416322/98961029-1faa2d80-252b-11eb-8b24-b5d2e602e810.PNG)
@terjeio Thanks
