### ISSUE TITLE
COMPATIBILITY_LEVEL 2 build errors

### ISSUE THREAD

**Issue by phil-barrett** [terjeio/grblHAL#116]
grblHAL_Teensy4 built with `#define COMPATIBILITY_LEVEL 2`  in config.h gets lots of errors. Set to 1, it builds with no errors.

**Comment by terjeio** [comment]
Master or test branch? There is a regression in the test branch in gcode.c - results in a single error for me.

**Comment by phil-barrett** [comment]
Sorry, Master.

**Comment by terjeio** [comment]
Master builds for me with downloaded files (iMXRT1062 driver) and all features except SPINDLE_HUANYANG enabled. More details needed:

Which driver.
Features enabled in my_machine.h.
Some of the error messages (not warnings).
