### ISSUE TITLE
Backlash compensation?

### ISSUE THREAD

**Issue by Harvie** [terjeio/grblHAL#117]
I've noticed some mentions of backlash compensation being possible with grblHAL, is that true? How can i enable that?

**Comment by terjeio** [comment]
Yep, uncomment this line:

https://github.com/terjeio/grblHAL/blob/b7863758a81774dbd8ecd3d31aa2ca2da9676d40/grbl/config.h#L281

Note that I have not tested this myself.

BTW what is the status of issue #68? Did you ever get around to test the plugin I made?
