### ISSUE TITLE
Web socket: Blue Pill+ Esp8266 Intermittent connection

### ISSUE THREAD

**Issue by gitxmax** [terjeio/grblHAL#121]
Followed this guide http://lasergrbl.com/usage/wifi-with-esp8266/ , to control my laser engraver remotely.
It sort of works, but keeps constantly disconnecting.
Anything can be done?

**Comment by terjeio** [comment]
The WiFi connection is unstable? If so the there is nothing I can do about that. You have to contact the supplier of the board for help.
