### ISSUE TITLE
PS2 keyboard plugin

### ISSUE THREAD

**Issue by Harvie** [terjeio/grblHAL#123]
Might be interresting to make clone of keypad plugin to use ps2 keyboard instead of i2c keypad

https://github.com/terjeio/grblHAL/tree/master/plugins/keypad

![image](https://user-images.githubusercontent.com/276504/100163622-65b1aa80-2eb6-11eb-8bc8-6d878bcdd564.png)

**Comment by terjeio** [comment]
You want to give it a try?

**Comment by Harvie** [comment]
it actualy seems quite easy to implement, so maybe later :-)
first i have to fix compatibility issues between bCNC and grblHAL. people reported some issues when running more than 3 axes, but that should be easy fix. But today i noticed the overrides are not working and that i cannot unpause paused job, i'll have to check what changed since original grbl protocol...

**Comment by terjeio** [comment]
Create at PR over at the [new repo](https://github.com/grblHAL) if you ever get around to implement this. Or perhaps a new plugin submodule is needed?
