### ISSUE TITLE
Simple Machine Definition

### ISSUE THREAD

**Issue by phil-barrett** [terjeio/grblHAL#17]
I agree with your thoughts on simple machine definition. 

I will call the TH pins "front side" from now on just to be consistent with back side.

There are a couple of issues to be resolved:

1. Is coolant (flood and/or mist) in the SM definition? I think we don't need both but one would be good.
2. I'm fine with front side pins for i2c as part of SM. channel 0 or 1?  I suggest channel 1 (pins 18, 19). 
3. Is door an SM pin? I'm torn on this. If someone is going to the trouble of building an enclosure they are probably capable of using backside pins. On the other hand, it's a good safety feature in many cases.
4. Do we need Limit A as an SM pin? I think that could be pushed to the backside.

If we keep I2C and mist on the front side, there is no room for door.  Which is more important for a simple machine, door or mist?

By the way in driver.h, door (SAFETY_DOOR_PIN) is on 17 as is CYCLE_START_PIN.

**Comment by phil-barrett** [comment]
Still thinking about these issues.  I'd like to address the question of I2C vs other pins in the simple machine definition. I'm willing to go along with I2C on the front side but that does cause either coolant or door to be pushed to the back. 

So, the question is what is the priority order for I2C, Door and Coolant?

**Comment by terjeio** [comment]
> So, the question is what is the priority order for I2C, Door and Coolant?

Select some pins for dual purposes and add config options so the end user can decide? If USB is used then the UART pins may be reconfigured.

**Comment by phil-barrett** [comment]
Good point about RX and TX. I had assumed they were sacred but that's old school arduino thinking. USB will be pretty common use case for a simple machine. 

I wonder about how a network interface would work for teensy based system. if that's possible at all.  Certainly it's my goal to move to ethernet connection on my next machine.  But then perhaps that's not so simple...

**Comment by terjeio** [comment]
There is an Ethernet MAC on the MCU but I belive I read somewhere that the pins were not brought out. If true the only option is an external controller with a serial interface?

Two of the grblHAL drivers supports ethernet and one wifi so a fair bit of the needed codebase is already present.
