### ISSUE TITLE
Support of M66?

### ISSUE THREAD

**Issue by mattbue** [terjeio/grblHAL#172]
Hi, in the list of supported g codes there is M66 mentioned.
I'm trying to use the command with GCode Sender Beta8 and Phil Barrets grblHAL-teensy-4.x board.

`M66 P0 L3 Q10`

In GCode Sender Beta8 i get error:20 `Unsupported or invalid g-code command found in block.`

Do i need to configure something to use the command?
Or do i use an unsupported syntax?

Thanks!

**Comment by terjeio** [comment]
Support was added in [test branch](https://github.com/terjeio/grblHAL/blob/test) build [20201219](https://github.com/terjeio/grblHAL/blob/test/changelog.md). Check `$I` output or see _Help > About_ in the sender for version installed.
