### ISSUE TITLE
Potential error in grbl status report response

### ISSUE THREAD

**Issue by Hamoudy99** [terjeio/grblHAL#203]
reading through the [wiki ](https://github.com/terjeio/grblHAL/wiki/Report-extensions) when I noticed this:

>`P` - probe triggered
`O` - probe disconnected, new
`X` - X limit switch asserted
`Y` - Y limit switch asserted
`Z` - Y limit switch asserted `<< typo`
`A` - A limit switch asserted, new
`B` - B limit switch asserted, new `<< duplicate`
`C` - C limit switch asserted, new
`D` - Door switch asserted
`R` - Reset switch asserted
`H` - Feed hold switch asserted
`S` - Cycle start switch asserted
`E` - E-Stop switch asserted, new
`B` - Block delete switch asserted, new `<< duplicate`
`T` - Optional program stop switch asserted, new

not sure if the code for this is implemented yet, but the duplicate `B` sounds like it could be an issue depending on how senders are coded. I don't fully understand the status report formats tho, so I could be wrong

**Comment by terjeio** [comment]
Thanks, duplicate was bad - not used yet so good to correct now. Block delete will be changed to `L`.
I have added two more signal letters, `W`  for motor warning and `M` for motor fault

A new element `FW` has been added for detecting what kind of firmware is running on the controller. The Wiki page has been updated with these changes.
