### ISSUE TITLE
Did anyone sucessfully compiled code for Arduino IDE using ESP32

### ISSUE THREAD

**Issue by krupis** [terjeio/grblHAL#216]
Please someone share their experience compiling this project for using Arduino IDE.

Using this as a guide:
https://github.com/terjeio/grblHAL/wiki/Compiling-GrblHAL

I am getting stuck at this :

Load the selected grblHAL_xxx folder into the Arduino IDE as a Library.

First of all, there is no such thing as grblHAL_xxx (where xxx is the driver name).

I am not sure what file should I add as a library?

In my grlbHAL-master, there is a drivers folder. Inside drivers, I have ESP32 folder which I assume I have to add as a library:
![Screenshot 2021-01-28 at 09 36 52](https://user-images.githubusercontent.com/22237034/106105263-5f58dc80-614c-11eb-8105-d11029f55366.png)

After adding this as a library, I can confrim that it appears in arduino library fodlers, but I am not able to confrim the 2nd step;

![Screenshot 2021-01-28 at 09 43 04](https://user-images.githubusercontent.com/22237034/106105837-4d2b6e00-614d-11eb-818b-33cd717788cd.png)

You can confirm that the library has been added by checking the File > Examples menu, scroll to the bottom of the list where you should see grblHAL for xxx.

Unfortunately, I cannot see this library under the examples menu:
![Screenshot 2021-01-28 at 09 44 10](https://user-images.githubusercontent.com/22237034/106105908-692f0f80-614d-11eb-8346-3d55cfd41a75.png)

That is most likely because inside drivers -> ESP32 there are no such folder "examples" because I believe Arduino IDE is looking for that folder and displays it if its found. But then it does not make any sense. Is that the wrong project that I have downloaded?

**Comment by krupis** [comment]
I have now found a simmilar port for grbl for ESP32:
https://github.com/bdring/Grbl_Esp32

Are these different grbl firmwares? I can clearly see that this one has got an Arduino type project .ino in it and should be able to compile on arduino?

**Comment by terjeio** [comment]
> Are these different grbl firmwares?

Yes.

> I can clearly see that this one has got an Arduino type project .ino in it and should be able to compile on arduino?

You should.

grblHAL is _not_ a Arduino type project, it uses the standard ESP IDF build system. Arduino uses that too so it should be possible to add a .ino-file for grblHAL too depending on which version of ESP IDF Arduino uses.

ESP IDF v4 has a CMake plugin for Eclipse, I will look into converting grblHAL to v4 when I get my new development machine (to be delivered soon). Possibly also adding a .ino file for the Arduino as well. Unfortunately there is no room on my current machine to do that now - disks are full.

**Comment by krupis** [comment]
Thanks for clearing that out so fast. Il be still trying to get it to compile on esp-idf v3.3
