### ISSUE TITLE
SAMD21G18a compile error

### ISSUE THREAD

**Issue by klembaris** [terjeio/grblHAL#224]
Hi, when i try compile driver for SAMD21 got an error:
![samd21error](https://user-images.githubusercontent.com/17252320/106385193-9db5fc00-63d7-11eb-9186-85fbb49a1f94.png)

**Comment by terjeio** [comment]
So somebody has defined `synchronized` as a macro in the Arduino framework disallowing its use in code?

It is not in the 1.6.12 version I compile against. And it should be fixed by filing a bug report for the framework to get it fixed there?

**Comment by klembaris** [comment]
OK ill try 1.6.12 version.

**Comment by terjeio** [comment]
I have added a note about this in the driver readme. It seems likely that the framework is not going to be fixed :-(
