### ISSUE TITLE
Correct pin assignment map for SAM3X8E Due Ramps 1.6

### ISSUE THREAD

**Issue by MARIOBASZ** [terjeio/grblHAL#249]
Little mistake
Change in the pin plane, according to Ramps 1.6 map:
Feed hold from A4 to A5
Cycle Start from A5 to A4.
Terjeio, congratulations and thank you for all the work invested. I'll start testing it.
Hug.

**Comment by terjeio** [comment]
> Change in the pin plane, according to Ramps 1.6 map:

Map from where?

**Comment by MARIOBASZ** [comment]
in file showing pin assignment schematic

**Comment by MARIOBASZ** [comment]
With Arduino Due
