### ISSUE TITLE
Feed Hold button working principle

### ISSUE THREAD

**Issue by krupis** [terjeio/grblHAL#272]
Hello. I would to ask regarding the feed hold button and how it supposed to work properly. I have wired the button in NC configuration and it is active HIGH. 

When the button is pressed during the cnc operation, the machine motors does not stop immediately. Sometimes it even takes 1 or 2 seconds to stop. Can someone explain me what is happening? Does it have to finish a g code line before stopping or what? Is that the expected behaviour?

If I want to stop the machine immediately , the only option is to trigger an emergency button  (soft reset)?

**Comment by phil-barrett** [comment]
Hold won't stop immediately, deceleration is needed.  How long it takes depends on your acceleration settings and how fast it was moving when you hit Hold. It will stop in the middle of a GCode block - you can test that pretty easily.
