### ISSUE TITLE
64 pin STM32F103RC

### ISSUE THREAD

**Issue by MeKeCNC** [terjeio/grblHAL#319]
Hi
Is it possible to support, 64 pin STM32F103RC with 256 Kbytes of Flash memory? so I want to use BTT SKR MINI E3 V2.0 3D printer board.
https://www.bigtree-tech.com/products/bigtreetech-skr-mini-e3-v2-0-32-bit-control-board-integrated-tmc2209-uart-for-ender-3.html

**Comment by terjeio** [comment]
This repo will not be updated anymore, and I have already answered your [question](https://github.com/grblHAL/STM32F1xx/issues/2) at the new repo.
