### ISSUE TITLE
delta robot

### ISSUE THREAD

**Issue by NgocLe97** [terjeio/grblHAL#326]
can i use grblHAL with delta robot?

**Comment by terjeio** [comment]
Currently no, a kinematics plugin has to be added for that. There are a couple available that shows how it can be done:

[CoreXY](https://github.com/grblHAL/core/blob/master/corexy.c)
[Wall plotter](https://github.com/grblHAL/core/blob/master/wall_plotter.c)

I guess the algorithm/more or less usable code can be found in other projects...

**Comment by NgocLe97** [comment]
oh thanks a lot, i will try
