### ISSUE TITLE
Feed Rate issues with STM32F1xx driver

### ISSUE THREAD

**Issue by shaise** [terjeio/grblHAL#33]
Hi,

When setting very low feed rates (F <= 20 mm/min) The step speed calculation goes wrong sending the CNC to very high/random speeds. (happens on a 400 steps/mm axis with AMASS = 3)
Solution: use stepperCyclesPerTickPrescaled always (instead of stepperCyclesPerTick) as even when AMASS is used, cycles_per_tick can be higher then 65535.

shai

**Comment by terjeio** [comment]
Thanks, will have to look into this as I may have messed up code in the core (in stepper.c).

**Comment by shaise** [comment]
From what I investigated, I think the stepper.c code is ok, Its just a very large (> 16bit) wait between pulses, and the timer is only 16 bit. 
Unless of course you planed to handle it with extra interrupts between pulses.

**Comment by shaise** [comment]
Works great now, thanks!
