### ISSUE TITLE
3rd order motion planner “S-curve” acceleration request

### ISSUE THREAD

**Issue by Tardusas** [terjeio/grblHAL#335]
Not an issue but an iquiry/request. 

Is there a road map to implement a plugin for more advanced motion planner using acceleration S-curve?

Maybe somebody has been working on it?

It would be nice to shift from g2core to grblHAL with advanced motion planner.

**Comment by terjeio** [comment]
> Is there a road map to implement a plugin for more advanced motion planner using acceleration S-curve?

No, not yet.

> Maybe somebody has been working on it?

Not that I am aware of, you can do it?

BTW this repo is no longer maintained, start a [discussion at the new](https://github.com/grblHAL/core/discussions) instead if you want to keep this active.
