### ISSUE TITLE
softlimit deaktivate only for the rotationsaxes, a-achses

### ISSUE THREAD

**Issue by S2000Stefan** [terjeio/grblHAL#36]
Hello terjeio,

it is possible when the soft limit $20=1 is switched on that the rotationaxis (a-axis) 
is deactivated by entering 0 in $133=0?
The background is that I mostly work in a helical milling. Machine in one direction with a lot of rotations and that is not possible with soft limits on. But like to use soft limits in xyz  ;)

BTW i cannot invert the probe pin $6=0/1.

Greeting
Stefan

**Comment by terjeio** [comment]
It should be possible, will have to look into that.

Which driver are you using? I need to know since pin inversion is not done in the common core.

**Comment by S2000Stefan** [comment]
Thank you.
My driver is: STM32F1xx Bluepill

**Comment by terjeio** [comment]
Fix committed for driver.
Added skip of 0 max travel axes in soft limits check.
I have a TODO note in the source about adding check for homed axes as well, I think I should add that too since grblHAL keeps track of which axes are homed. May I ask if you home the A-axis?

**Comment by S2000Stefan** [comment]
Many many Thanks,
Although I was only able to do short tests today, everything is working as desired. :)
No i don't home the A-axis, see no sense in it for me.
Many thanks again.
Cheers
Stefan
