### ISSUE TITLE
In v20200603 grblHAL-master/drivers/IMXRT1062/main/driver.c

### ISSUE THREAD

**Issue by hsh002** [terjeio/grblHAL#56]
in file             [grblHAL-master/drivers/IMXRT1062/main/driver.c]
Line 939        [IOInitDone = settings->version == 15;]

Replace  with [IOInitDone = (settings->version == SETTINGS_VERSION);]

SETTINGS_VERSION defined to 16 in grblHAL-master/grbl/settings.h
Thanks a lot for your works.

**Comment by terjeio** [comment]
Oops - something went wrong in updating github from my subversion master, will fix.

> Replace with [IOInitDone = (settings->version == SETTINGS_VERSION);]

No, this defeats the purpose of this test which is to trap breaking changes. This time there were none but sometimes there are...

Thanks for reporting.
