### ISSUE TITLE
Mask for limits

### ISSUE THREAD

**Issue by MARIOBASZ** [terjeio/grblHAL#65]
Trying to invert pin logic for limits with mask, I was assuming you could invert for all six axes, however it only works for X and Z.
$ 5 = 7 (111) reverses Z Y X
I assumed that 63 (111111) reversed the limits of the six axes
however, I cannot invest S - R - H
Is there a way to invest them?
The alarm continues to show R H S

**Comment by phil-barrett** [comment]
Do you have 6 axes set up?You need to enable additional axes in grbl/config.h.  By default, there are only 3.  S, R and H are inputs for Cycle/Start, Reset and Feed/Hold. $14 inverts the control pins. Reset is 1, Hold is 2 and Start 4 so you would enter $14 = 7.

**Comment by MARIOBASZ** [comment]
Thank you very much, phil-barret.
I will try as you told me.
