### ISSUE TITLE
Raspberry PI support

### ISSUE THREAD

**Issue by Harvie** [terjeio/grblHAL#69]
![image](https://user-images.githubusercontent.com/276504/85437603-25f33980-b58b-11ea-8a7a-9151cc1157db.png)

I wonder if it would be possible to compile grblHAL as Linux binary for Raspberry PI with realtime linux kernel. Linux GPIO drivers are already available for raspberry pi.

That way it would be possible to run bCNC on raspberry pi connected to microcontroller with grblHAL. Or merge it to single device where grblHAL would run as process with maximal (realtime) priority and sender GUI (lower priority) would connect to it using socket. User would be able to choose which setup fits him the most (single CPU or dedicated uC).

**Comment by terjeio** [comment]
> I wonder if it would be possible to compile grblHAL as Linux binary for Raspberry PI ...

To find out try to make a driver. Socket communication should be easy, the rest [perhaps not so](https://www.raspberrypi.org/forums/viewtopic.php?t=202648)?

I once considered making a bare metal driver for the PI, possibly using the[ GPU for the realtime stuff](https://github.com/hoglet67/PiTubeDirect/wiki). To many ideas, too little time to implement them...
