### ISSUE TITLE
Unknown type name Pio

### ISSUE THREAD

**Issue by Symeth** [terjeio/grblHAL#78]
Hi

i found error when compiling
with setting

config.h :
#define COMPATIBILITY_LEVEL 2
#define N_AXIS 4 // Number of axes

default.h
#if DEFAULT_HOMING_ENABLE
#define HOMING_CYCLE_0 (Z_AXIS_BIT|A_AXIS_BIT)             // REQUIRED: First move Z to clear workspace.

driver.h
#define BOARD_RAMPS_16

if compile getting error with message
Unknown type name Pio

thanks
Rizki

**Comment by terjeio** [comment]
Which driver? I have checked the SAM3X8E driver and it compiles ok for me with the test branch.

**Comment by terjeio** [comment]
More details needed, reopen if this still an issue.
