### ISSUE TITLE
test branch 30.08.20 STM32F1 USB error

### ISSUE THREAD

**Issue by S2000Stefan** [terjeio/grblHAL#84]
during the test branch on 29.08. and 30.08., i got an usb-error. Driver is STM32F1xx
last working version is from 15.08.
![usb_fehler_b](https://user-images.githubusercontent.com/35189051/91660573-120e0b80-ead7-11ea-840a-184f3c417205.jpg)

**Comment by terjeio** [comment]
A copy-paste error... You can replace USB_ENABLE with USB_SERIAL in Src/driver.c util I get around to commit a fix.

**Comment by S2000Stefan** [comment]
Thanks for the very quick answer, unfortunately it did not fix the problem.

**Comment by S2000Stefan** [comment]
sorry my mistake you had to change it three times 
:)
