### ISSUE TITLE
Communicate via UART with iMXRT1062/Teensy 4?

### ISSUE THREAD

**Issue by Elmi77** [terjeio/grblHAL#97]
Hi,

is there a possibility to configure the iMXRT1062/Teensy port to not to use USB for communication but UART instead? If yes: where/how is this possible?

Thanks! :-)

**Comment by terjeio** [comment]
https://github.com/terjeio/grblHAL/blob/a08601881ebdb6c519fbfc228e11d5f65dd4f755/drivers/IMXRT1062/grblHAL_Teensy4/src/my_machine.h#L48

UART 1 is used when enabled, pin 0 = RX - 1 = TX

**Comment by Elmi77** [comment]
Great, thanks! :-)
